### ISSUE TITLE
S2SD (Simultaneous Similarity-based Self-Distillation)

### ISSUE THREAD

**Issue by sid4sal** [ExplainableML/LanguageGuidance_for_DML#5]
**Issue 1**:-
When the loss is set as `--loss s2sd`, following error occurs
```
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    criterion, to_optim = criteria.select(opt.loss, opt, to_optim, batchminer)
  File "/content/criteria/__init__.py", line 32, in select
    criterion = loss_lib.Criterion(**loss_par_dict)
  File "/content/criteria/s2sd.py", line 67, in __init__
    self.target_criteria = nn.ModuleList()
NameError: name 'nn' is not defined
```
solution of Issue 1:-
In `/criteria/s2sd.py` change the 2nd line from `import torch` to `import torch, torch.nn as nn`

**Issue 2**
The performance of the model degrades (Loss increases and recall decreases) when training, if the flag `--loss_s2sd_pool_aggr` is set.
![Screenshot 2022-08-09 151920](https://user-images.githubusercontent.com/30002457/183619469-80f661bf-1380-4bad-a6ab-515bc7383ed3.png)
```
!python main.py \
--seed 2 --no_train_metrics \
--log_online --group cub200-rn128_s2sd-msim_plg --project LanguageGuidance \
--wandb_key "your_wandb_key" \
--gpu 0 --source_path "/content/dataset" --dataset cub200 \
--n_epochs 300 --tau 300 --gamma 1 \
--arch resnet50_frozen_normalize --embed_dim 128 --bs 108 \
--loss s2sd --loss_s2sd_source multisimilarity --loss_s2sd_target multisimilarity \
--loss_s2sd_feat_distill --loss_s2sd_feat_w 125 --loss_s2sd_feat_distill_delay 0 --loss_s2sd_pool_aggr \
--language_distill_w 1.5 --language_pseudoclass
```
When I run the above code, it outputs the following:

<details>

  <summary>
    This outputs:- (<i>click to expand</i>)
  </summary>

```java
Dataset Setup: 
#Classes: Train (100) | Val (X) | Test (100)

Dataset:	 CUB200
Objective:	 S2SD
Batchminer:	 N/A
Backbone:	 RESNET50_FROZEN_NORMALIZE (#weights: 23770304)
100%|████████████████████████████████████████| 338M/338M [00:03<00:00, 113MiB/s]


Getting ImageNet pseudolabels...: 100% 55/55 [01:00<00:00,  1.10s/it]
Getting language embeddings...
Retrieved 500 language embeddings!

-----

Epoch 0 Training...:   0% 0/54 [00:00<?, ?it/s]Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 0: Mean Loss [0.9527]: 100% 54/54 [01:11<00:00,  1.33s/it, DML Loss: 0.9527]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:44<00:00,  1.23it/s]
Out-Type: embeds:
e_recall@1: 0.5187 | e_recall@2: 0.6553 | e_recall@4: 0.7681 | e_recall@10: 0.8778 | nmi: 0.5884 | f1: 0.2594 | mAP_1000: 0.2036


Total Epoch Runtime: 118.87s
Epoch 1 Training...:   0% 0/54 [00:00<?, ?it/s]
-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 1: Mean Loss [0.9094]: 100% 54/54 [01:10<00:00,  1.30s/it, DML Loss: 0.9094]

Embedding Data...:   0% 0/55 [00:00<?, ?it/s]
Embedding Data...: 100% 55/55 [00:41<00:00,  1.31it/s]
Out-Type: embeds:
e_recall@1: 0.5463 | e_recall@2: 0.6696 | e_recall@4: 0.7854 | e_recall@10: 0.8856 | nmi: 0.5932 | f1: 0.2695 | mAP_1000: 0.2133


Total Epoch Runtime: 113.52s

-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 2: Mean Loss [0.9064]: 100% 54/54 [01:10<00:00,  1.30s/it, DML Loss: 0.9064]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:41<00:00,  1.31it/s]
Out-Type: embeds:
e_recall@1: 0.5300 | e_recall@2: 0.6588 | e_recall@4: 0.7670 | e_recall@10: 0.8798 | nmi: 0.6045 | f1: 0.2814 | mAP_1000: 0.2168


Epoch 3 Training...:   0% 0/54 [00:00<?, ?it/s]

-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 3: Mean Loss [0.9069]: 100% 54/54 [01:09<00:00,  1.29s/it, DML Loss: 0.9069]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:41<00:00,  1.33it/s]
Out-Type: embeds:
e_recall@1: 0.4558 | e_recall@2: 0.5802 | e_recall@4: 0.6978 | e_recall@10: 0.8324 | nmi: 0.5363 | f1: 0.2132 | mAP_1000: 0.1615

Epoch 4 Training...:   0% 0/54 [00:00<?, ?it/s]
Total Epoch Runtime: 112.27s

-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 4: Mean Loss [0.9146]: 100% 54/54 [01:09<00:00,  1.29s/it, DML Loss: 0.9146]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:41<00:00,  1.32it/s]
Out-Type: embeds:
e_recall@1: 0.3823 | e_recall@2: 0.5039 | e_recall@4: 0.6259 | e_recall@10: 0.7633 | nmi: 0.4868 | f1: 0.1741 | mAP_1000: 0.1220


Total Epoch Runtime: 112.71s

-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 5: Mean Loss [0.9156]: 100% 54/54 [01:09<00:00,  1.30s/it, DML Loss: 0.9156]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:40<00:00,  1.34it/s]
Out-Type: embeds:
e_recall@1: 0.1460 | e_recall@2: 0.2233 | e_recall@4: 0.3160 | e_recall@10: 0.4752 | nmi: 0.2999 | f1: 0.0485 | mAP_1000: 0.0329

Epoch 6 Training...:   0% 0/54 [00:00<?, ?it/s]
Total Epoch Runtime: 112.08s

-----

Running with learning rates 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05 | 1e-05...
Epoch (Train) 6: Mean Loss [0.9302]: 100% 54/54 [01:10<00:00,  1.30s/it, DML Loss: 0.9302]

Computing Testing Metrics...
Embedding Data...: 100% 55/55 [00:41<00:00,  1.33it/s]
Out-Type: embeds:
e_recall@1: 0.1242 | e_recall@2: 0.1864 | e_recall@4: 0.2667 | e_recall@10: 0.4105 | nmi: 0.2768 | f1: 0.0380 | mAP_1000: 0.0247
```

</details>

**Comment by Confusezius** [comment]
Thanks for noticing! I've fixed issue 1 :). Regarding Issue 2, I mostly used the standard S2SD feature distillation setup - if ignoring the joint max- and averagepool-matching (i.e. discarding `--loss_s2sd_pool_aggr`) helps, that's good additional news! Do you have some numbers for the comparison?

**Comment by sid4sal** [comment]
Hi! @Confusezius , I created a [wandb report Here](https://wandb.ai/sid4sal/LanguageGuidance/reports/Language-Guidance-for-DML--VmlldzoyNDA0ODY3?accessToken=foya96xmc2e6dau4g4a5tcmg7jvo3k95qmfvxa0sz4iwvb0gzy4dv3cz4l0j6rej). I trained the models with `--loss_s2sd_pool_aggr` only for a few epochs (5-10). I have plotted the graphs for all my runs; scroll down to the "Issue" section for data on the models with `--loss_s2sd_pool_aggr`.
Here is the [link to the Google Colab](https://colab.research.google.com/drive/1saLKOehHjpo5I1A3Xa2VS_jkAA6zZUAB?usp=sharing) that I made to run the code.

**Comment by Confusezius** [comment]
I see, so it generally doesn't seem to converge with the *current* hyperparameter setting when the aggregation flag is set, but performs very well without it. Thanks for pointing this out! I'll have to check my runs and adapt the sample runs if there was a copy error :).

It would be interesting to see if training recovers for the full training run though, and if this is just a convergence issue at the beginning of training.

**Comment by Confusezius** [comment]
Ok I've checked my runs, and I see a similar drop at the beginning of training for large S2SD-regularization weights, though it generally recovers very well as training progresses. For the provided hyperparameter setting I don't see such a dip in my runs, but you can check what happens when utilising a smaller `--loss_s2sd_feat_w`, such as e.g. 50 or 80. You should still get very strong benefits (maybe slightly less) without the dip in convergence :).

**Comment by sid4sal** [comment]
@Confusezius Thank you so much for looking into the issue :)
